exclude: ^(doc|scripts).*$
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: requirements-txt-fixer
    -   id: detect-private-key
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.620
    hooks:
    -   id: mypy
